package com.discovering.carrito_de_compras;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Descuentos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("% descuento del primer item de la compra para un nuevo cliente")
	@org.kie.api.definition.type.Label("1ra Compra")
	private double primeraCompra;

	@org.kie.api.definition.type.Description("% descuento para computacion")
	@org.kie.api.definition.type.Label("Computacion")
	private double computacion;

	@org.kie.api.definition.type.Description("% descuento para celulares")
	@org.kie.api.definition.type.Label("Celulares")
	private double celulares;

	@org.kie.api.definition.type.Description("% descuento para videojuegos")
	@org.kie.api.definition.type.Label("Videojuegos")
	private double videojuegos;

	@org.kie.api.definition.type.Description("% descuento para electronica")
	@org.kie.api.definition.type.Label("Electronica")
	private double electronica;

	@org.kie.api.definition.type.Description("% descuento para electrodomesticos")
	@org.kie.api.definition.type.Label("Electrodomesticos")
	private double electrodomesticos;

	@org.kie.api.definition.type.Description("% descuento cupon proxima compra")
	@org.kie.api.definition.type.Label("Cupon Descuento Proxima Compra")
	private double cuponDescuentoProximaCompra;
	@org.kie.api.definition.type.Description("% descuento primer par de productos iguales (si hay)")
	@org.kie.api.definition.type.Label("Cumpleaños Primer Par")
	private double cumplePrimerPar;

	@org.kie.api.definition.type.Description(value = "% descuento cumpleaños de la compra")
	@org.kie.api.definition.type.Label(value = "Descuento Cumpleaños")
	private double cumpleDescuentoCompra;
	public Descuentos() {
	}

	public double getPrimeraCompra() {
		return this.primeraCompra;
	}

	public void setPrimeraCompra(double primeraCompra) {
		this.primeraCompra = primeraCompra;
	}

	public double getComputacion() {
		return this.computacion;
	}

	public void setComputacion(double computacion) {
		this.computacion = computacion;
	}

	public double getCelulares() {
		return this.celulares;
	}

	public void setCelulares(double celulares) {
		this.celulares = celulares;
	}

	public double getVideojuegos() {
		return this.videojuegos;
	}

	public void setVideojuegos(double videojuegos) {
		this.videojuegos = videojuegos;
	}

	public double getElectronica() {
		return this.electronica;
	}

	public void setElectronica(double electronica) {
		this.electronica = electronica;
	}

	public double getElectrodomesticos() {
		return this.electrodomesticos;
	}

	public void setElectrodomesticos(double electrodomesticos) {
		this.electrodomesticos = electrodomesticos;
	}

	public double getCuponDescuentoProximaCompra() {
		return this.cuponDescuentoProximaCompra;
	}

	public void setCuponDescuentoProximaCompra(
			double cuponDescuentoProximaCompra) {
		this.cuponDescuentoProximaCompra = cuponDescuentoProximaCompra;
	}

	public double getCumplePrimerPar() {
		return this.cumplePrimerPar;
	}

	public void setCumplePrimerPar(double cumplePrimerPar) {
		this.cumplePrimerPar = cumplePrimerPar;
	}

	public double getCumpleDescuentoCompra() {
		return this.cumpleDescuentoCompra;
	}

	public void setCumpleDescuentoCompra(double cumpleDescuentoCompra) {
		this.cumpleDescuentoCompra = cumpleDescuentoCompra;
	}

	public Descuentos(double primeraCompra, double computacion,
			double celulares, double videojuegos, double electronica,
			double electrodomesticos, double cuponDescuentoProximaCompra,
			double cumplePrimerPar, double cumpleDescuentoCompra) {
		this.primeraCompra = primeraCompra;
		this.computacion = computacion;
		this.celulares = celulares;
		this.videojuegos = videojuegos;
		this.electronica = electronica;
		this.electrodomesticos = electrodomesticos;
		this.cuponDescuentoProximaCompra = cuponDescuentoProximaCompra;
		this.cumplePrimerPar = cumplePrimerPar;
		this.cumpleDescuentoCompra = cumpleDescuentoCompra;
	}

}