package com.discovering.carrito_de_compras;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Producto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cantidad")
	@org.kie.api.definition.type.Description("Items del producto de la compra")
	private java.lang.Integer cantidad;

	@org.kie.api.definition.type.Label("Categoria")
	@org.kie.api.definition.type.Description("Categoria del producto")
	private java.lang.String categoria;

	@org.kie.api.definition.type.Label("Descripcion")
	@org.kie.api.definition.type.Description("Descripcion del producto")
	private java.lang.String detalle;

	@org.kie.api.definition.type.Label("Precio")
	@org.kie.api.definition.type.Description("Precio unitario Final")
	private double precio;

	@org.kie.api.definition.type.Label("Descuento")
	@org.kie.api.definition.type.Description("Porcentaje de descuento sobre el item la compra")
	private double descuento;

	@org.kie.api.definition.type.Description("Detalle de descuentos o cupones obtenidos")
	@org.kie.api.definition.type.Label("Detalle Descuentos")
	private java.util.List<java.lang.String> obsDescuentos;

	@org.kie.api.definition.type.Description("Aplica el descuento del primer item de la compra")
	@org.kie.api.definition.type.Label("Descuento Primera Compra")
	private java.lang.Boolean aplicaDescuentoPrimeraCompra;

	@org.kie.api.definition.type.Description("Indica si aplica un descuento por cumpleaños.")
	@org.kie.api.definition.type.Label("Aplica Desc Cumpleaños")
	private java.lang.Boolean aplicaDescuentoCumple;

	@org.kie.api.definition.type.Description(value = "% descuento en la segunda unidad (cumpleaños cliente)")
	@org.kie.api.definition.type.Label(value = "Desc 2da Unidad")
	private double descuento2daUnidadCumple;

	public Producto() {
	}

	public java.lang.Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(java.lang.Integer cantidad) {
		this.cantidad = cantidad;
	}

	public java.lang.String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(java.lang.String categoria) {
		this.categoria = categoria;
	}

	public java.lang.String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(java.lang.String detalle) {
		this.detalle = detalle;
	}

	public java.util.List<java.lang.String> getObsDescuentos() {
		if (this.obsDescuentos == null) {
			this.obsDescuentos = new java.util.ArrayList();
		}
		return this.obsDescuentos;
	}

	public void setObsDescuentos(java.util.List<java.lang.String> obsDescuentos) {
		this.obsDescuentos = obsDescuentos;
	}

	public java.lang.Boolean getAplicaDescuentoPrimeraCompra() {
		return this.aplicaDescuentoPrimeraCompra;
	}

	public void setAplicaDescuentoPrimeraCompra(
			java.lang.Boolean aplicaDescuentoPrimeraCompra) {
		this.aplicaDescuentoPrimeraCompra = aplicaDescuentoPrimeraCompra;
	}

	public double obtenerImporteTotalItem() {
		double importeTotalSinDescuento = this.precio * this.cantidad - this.precio * this.descuento2daUnidadCumple / 100;
		return importeTotalSinDescuento
				- (importeTotalSinDescuento * this.descuento / 100);
	}

	public void addObservacionDescuento(String obs) {
		this.getObsDescuentos().add(obs);
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(double descuento) {
		this.descuento = descuento;
	}

	public java.lang.Boolean getAplicaDescuentoCumple() {
		return this.aplicaDescuentoCumple;
	}

	public void setAplicaDescuentoCumple(java.lang.Boolean aplicaDescuentoCumple) {
		this.aplicaDescuentoCumple = aplicaDescuentoCumple;
	}

	public double getDescuento2daUnidadCumple() {
		return this.descuento2daUnidadCumple;
	}

	public void setDescuento2daUnidadCumple(double descuento2daUnidadCumple) {
		this.descuento2daUnidadCumple = descuento2daUnidadCumple;
	}

	public Producto(java.lang.Integer cantidad, java.lang.String categoria,
			java.lang.String detalle, double precio, double descuento,
			java.util.List<java.lang.String> obsDescuentos,
			java.lang.Boolean aplicaDescuentoPrimeraCompra,
			java.lang.Boolean aplicaDescuentoCumple,
			double descuento2daUnidadCumple) {
		this.cantidad = cantidad;
		this.categoria = categoria;
		this.detalle = detalle;
		this.precio = precio;
		this.descuento = descuento;
		this.obsDescuentos = obsDescuentos;
		this.aplicaDescuentoPrimeraCompra = aplicaDescuentoPrimeraCompra;
		this.aplicaDescuentoCumple = aplicaDescuentoCumple;
		this.descuento2daUnidadCumple = descuento2daUnidadCumple;
	}
}